### ISSUE TITLE
07.09.2021 Improvements as discussed in daily meeting

### ISSUE THREAD

**Issue by fruttut** [OlenaMohylivska/Snake-game#3]
* `App.css` -- remove `-webkit-tap-highlight-color: transparent;`, it is not needed here
* Consider using SCSS
* Remove duplicate borders between adjacent field cells
* `GameFieldSize.tsx` -- please avoid using IDs to differentiate between target elements in callbacks unless performance gain outweighs this
* `combineReducers` shouldn't give you any trouble, the issue we discussed was most likely related to something else
* Let's use `react-router` and create three routes: the first (default) one should allow a user to choose board size and show how it would look like; the second one is the game itself; the third one is the scoreboard

**Comment by OlenaMohylivska** [comment]
PR - 'Issue1-resolving'
